config/routes.rb
Gestionemprunts::Application.routes.draw do
  resources :carts

	get "materials/by_type", :controller=>"materials", :action=>"by_type"
	root :to => "requests#new"
	resources :users
	resource :session, :only => [:new, :create, :destroy]
	get '/login' => "sessions#new", :as => "login"
	get '/logout' => "sessions#destroy", :as => "logout"
	
	get '/requests/newtwo' => "requests#newtwo"
	
	resources :complexdates
	resources :technicalfeatures
	resources :materials
	resources :requests
	resources :materialgroups
	resources :materialtypes
end

app/models/materialgroup.rb
class Materialgroup < ActiveRecord::Base
  
  validates_presence_of :label, :site
  
	has_and_belongs_to_many :users
end

app/controllers/materialgroups_controller.rb
class MaterialgroupsController < ApplicationController

  # GET /materialgroups
  # GET /materialgroups.json  
  def index
    @materialgroups = Materialgroup.all
    
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materialgroups }
     end
  end
  
  # GET /materialgroups/new
  # GET /materialgroups/new.json  
  def new
    @materialgroup = Materialgroup.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @materialgroup }
    end     
  end

  # GET /materialgroups/1/edit  
  def edit
    @materialgroup = Materialgroup.find(params[:id])
  end

  # GET /materialgroups/1
  # GET /materialgroups/1.json 
   def show
    @materialgroup = Materialgroup.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @materialgroup }
    end
  end

  # POST /materialgroups
  # POST /materialgroups.json  
  def create
    @materialgroup = Materialgroup.new(materialgroup_params)
    
    respond_to do |format|
      if @materialgroup.save
        format.html { redirect_to @materialgroup, notice: 'Materialgroup was successfully created.' }
        format.json { render json: @materialgroup, status: :created, location: @materialgroup }
      else
        format.html { render action: "new" }
        format.json { render json: @materialgroup.errors, status: :unprocessable_entity }
      end 
    end
  end

  # PUT /materialgroups/1
  # PUT /materialgroups/1.json  
  def update
    @materialgroup = Materialgroup.find(params[:id])
    
    respond_to do |format|  
      if @materialgroup.update_attributes(materialgroup_params)
          format.html { redirect_to @materialgroup, notice: 'Materialgroup was successfully updated.' }
          format.json { head :no_content }        
      else
         format.html { render action: "edit" }
         format.json { render json: @materialgroup.errors, status: :unprocessable_entity }
      end    
    end
  end
  
  private
  
  def materialgroup_params
    params.require(:materialgroup).permit(:label, :site)
  end
   
end

app/helpers/materialgroups_helper.rb
module MaterialgroupsHelper
end

app/views/materialgroups/_form.html.erb
<%= form_for(@materialgroup) do |f| %>
  <% if @materialgroup.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@materialgroup.errors.count, "error") %>
prohibited this user from being saved:</h2>
    <ul>
    <% @materialgroup.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
 <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  
 <div class="field">
    <%= f.label :site %><br />
    <%= f.text_field :site %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materialgroups/_materialgroup.html.erb
<%= div_for materialgroup do %>
  
	<div class="group"> <div class="groupfeature">Label : </div>	<%= simple_format materialgroup.label %> </div>


	<div class="group"> <div class="groupfeature">Site : </div>	<%= simple_format materialgroup.site %> </div>

	
	<%= link_to "Edit", edit_materialgroup_path(materialgroup) %>
	<%= link_to 'Destroy', materialgroup, method: :delete, data: { confirm: 'Are you sure?' } %>
  
<% end %>

app/views/materialgroups/edit.html.erb
<h3>Edit materialgroup</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', materialgroups_path %>

app/views/materialgroups/index.html.erb
<h3>List of technicalfeatures</h3>

<div id="materialgroups">
  <%= render @materialgroups %>
</div>

app/views/materialgroups/new.html.erb
<h3>New materialgroup</h3>

<%= render 'form' %>

<%= link_to 'Back', materialgroups_path %>

app/views/materialgroups/show.html.erb
<%= render @materialgroup %>