config/routes.rb
Gestionemprunts::Application.routes.draw do
  resources :carts

	get "materials/by_type", :controller=>"materials", :action=>"by_type"
	root :to => "requests#new"
	resources :users
	resource :session, :only => [:new, :create, :destroy]
	get '/login' => "sessions#new", :as => "login"
	get '/logout' => "sessions#destroy", :as => "logout"
	
	get '/requests/newtwo' => "requests#newtwo"
	
	resources :complexdates
	resources :technicalfeatures
	resources :materials
	resources :requests
	resources :materialgroups
	resources :materialtypes
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  has_many :cartlistmaterials
  has_many :cartitems, :through => :cartlistmaterials, :source => :technicalfeature
 
end

app/models/cartlistmaterial.rb
class Cartlistmaterial < ActiveRecord::Base
  
  belongs_to :cart
  belongs_to :technicalfeature
  
end

app/models/complexdate.rb
class Complexdate < ActiveRecord::Base
		
		#je me souviens plus si les heures sont obligatoires, il me semble que nn
		validates_presence_of :cdate
		
		belongs_to :request	
		belongs_to :complexdatetype
end

app/models/complexdatetype.rb
class Complexdatetype < ActiveRecord::Base
  
    validates_presence_of :label
    
    has_many :complexdates
    
end

app/models/material.rb
class Material < ActiveRecord::Base
  
  validates_presence_of :serialnumber
  validates_uniqueness_of :serialnumber
  
	has_and_belongs_to_many :requests
	
	belongs_to :materialgroup
	belongs_to :materialstatus
	belongs_to :technicalfeature
	
	has_one :type, :through=>:technicalfeature, :source=>:materialtype
end

app/models/materialgroup.rb
class Materialgroup < ActiveRecord::Base
  
  validates_presence_of :label, :site
  
	has_and_belongs_to_many :users
end

app/models/materialstatus.rb
class Materialstatus < ActiveRecord::Base
  
  validates_presence_of :label
  
  has_many :materials
end

app/models/materialtype.rb
class Materialtype < ActiveRecord::Base

	has_many :technicalfeatures
	has_many :associated_materials, :through=>:technicalfeatures, :source=>:materials
end

app/models/privilege.rb
class Privilege < ActiveRecord::Base

  validates_presence_of :label

	has_many :users

end

app/models/request.rb
class Request < ActiveRecord::Base	
  
  validates_presence_of :borrowmotive

  # Relations
	belongs_to :user
	has_many :complexdates
	has_and_belongs_to_many :materials
	belongs_to :requeststatus
	
end

app/models/requeststatus.rb
class Requeststatus < ActiveRecord::Base
  
  validates_presence_of :label
  
  has_many :requests
end

app/models/technicalfeature.rb
class Technicalfeature < ActiveRecord::Base
  
  has_many :materials
  belongs_to :materialtype
  
  has_one :technicalfeaturequantity
  
  has_many :cartlistmaterials
  has_many :techitems, :through => :cartlistmaterials, :source => :car
  
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

	# As the attribute :password does not exists as a column in the DB,
	# this defines an accessor attribute.
	# Like a local variable, just used to stock temporarely the not encrypted version of the password provided by the user.
	# Not persisted in the DB.
	attr_accessor :password

	# Global validation
	validates_presence_of :firstname, :lastname, :email
	
	# Email validations
	validates_uniqueness_of :email
	validates_length_of :email, :within => 5..50
	validates_format_of :email, :with =>  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	# Password validation
	validates_confirmation_of :password
	# validates_length_of :password, :within => 4..20
	# validates_presence_of :password, :if => :password_required?

	# Relations
	belongs_to :privilege
	has_many :requests
	has_many :appointments, :through=>:requests, :source=>:complexdates
	has_and_belongs_to_many :materialgroups
	
	# Always keep an encrypted version of the password in DB
	before_save :encrypt_new_password
	
	# Use --> User.authenticate('romain@gmail.com', 'password')
	# return the User object
	def self.authenticate(email, password)
		user = find_by_email(email)
		return user if user && user.authenticated?(password)
	end
	
	# Check the password
	def authenticated?(password)
		self.hashed_password == encrypt(password)
	end
	
	# Protected methods, used only inside the class
	protected
	
		# Create a new encrypted version of the password
		# Exit when local variable password is blank
		def encrypt_new_password
			return if password.blank?
			self.hashed_password = encrypt(password)
		end
		
		# Check if the password is required
		# When validating the password presence, if returns true, the :password local variable must be provided
		def password_required?
			hashed_password.blank? || password.present?
		end
		
		# Return the encrypted version of a string param
		def encrypt(string)
			Digest::SHA1.hexdigest(string)
		end
	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate
	before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json	
	def index
		@users = User.all
		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
     end
	end
	
  # GET /users/new
  # GET /users/new.json	
	def new
		@user = User.new
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end 		
	end
	
  # POST /users
  # POST /users.json	
	def create
		@user = User.new(user_params)
		
		respond_to do |format|
  		if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
  		else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
  		end
		end
	end

  # GET /users/1/edit	
	def edit
		@user = current_user
	end

  # PUT /users/1
  # PUT /users/1.json	
	def update
		@user = current_user
		
		respond_to do |format| 
  		if @user.update_attributes(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
  		else
         format.html { render action: "edit" }
         format.json { render json: @user.errors, status: :unprocessable_entity }
  		end
		end
	end
	
	private
		def set_user
			@user = current_user
		end

		def user_params
			params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/complexdates_helper.rb
module ComplexdatesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/materialtypes_helper.rb
module MaterialtypesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
      	<td><%= cart.cartlistmaterials </td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
 <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  
 <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= div_for user do %>
  <h3>
	<%= simple_format user.firstname %>
  </h3>
  
  <%= simple_format user.email %>
  <em><%= simple_format user.privilege.label %></em>
  <!-- <%= link_to "Edit", edit_user_path(user, :format=>:js), :remote=>true, :id=>'edit_user_link' %> -->
<% end %>

app/views/users/edit.html.erb
<h3>Edit user</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
$("<%= escape_javascript render(file: 'users/edit.html.erb') %>").insertAfter('.user');
$("#edit_user_link").hide();

app/views/users/index.html.erb
<h3>List of users (just to understand how to make MVC with user example)</h3>

<div id="users">
  <%= render @users %>
</div>

app/views/users/new.html.erb
<h3>New user</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render @user %>