config/routes.rb
Gestionemprunts::Application.routes.draw do
  resources :carts

	get "materials/by_type", :controller=>"materials", :action=>"by_type"
	root :to => "requests#new"
	resources :users
	resource :session, :only => [:new, :create, :destroy]
	get '/login' => "sessions#new", :as => "login"
	get '/logout' => "sessions#destroy", :as => "logout"
	
	get '/requests/newtwo' => "requests#newtwo"
	
	resources :complexdates
	resources :technicalfeatures
	resources :materials
	resources :requests
	resources :materialgroups
	resources :materialtypes
end

app/models/technicalfeature.rb
class Technicalfeature < ActiveRecord::Base
  
  has_many :materials
  belongs_to :materialtype
  
  has_one :technicalfeaturequantity
  
  has_many :cartlistmaterials
  has_many :techitems, :through => :cartlistmaterials, :source => :car
  
end

app/controllers/technicalfeatures_controller.rb
class TechnicalfeaturesController < ApplicationController

  # GET /technicalfeatures
  # GET /technicalfeatures.json
  def index
     @technicalfeatures = Technicalfeature.all
     
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @technicalfeatures }
     end
  end

  # GET /technicalfeatures/new
  # GET /technicalfeatures/new.json
  def new
   @technicalfeature = Technicalfeature.new
   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @technicalfeature }
    end 
  end
  
  # GET /technicalfeatures/1/edit
  def edit
   @technicalfeature = Technicalfeature.find(params[:id])
  end

  # GET /technicalfeatures/13
  # GET /technicalfeatures/13.json
  def show
    @technicalfeature = Technicalfeature.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @technicalfeature }
    end
  end

  # POST /technicalfeatures
  # POST /technicalfeatures.json
  def create
    @technicalfeature = Technicalfeature.new(technicalfeature_params)
    
    respond_to do |format|
      if @technicalfeature.save
        format.html { redirect_to @technicalfeature, notice: 'Technicalfeature was successfully created.' }
        format.json { render json: @technicalfeature, status: :created, location: @technicalfeature }
      else
        format.html { render action: "new" }
        format.json { render json: @technicalfeature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /technicalfeatures/1
  # PUT /technicalfeatures/1.json
  def update
    @technicalfeature = Technicalfeature.find(params[:id])
 
    respond_to do |format|   
      if @technicalfeature.update_attributes(technicalfeature_params)
          format.html { redirect_to @technicalfeature, notice: 'Technicalfeature was successfully updated.' }
          format.json { head :no_content }
      else
         format.html { render action: "edit" }
         format.json { render json: @technicalfeature.errors, status: :unprocessable_entity }
      end   
    end 
  end

  # DELETE /technicalfeatures/1
  # DELETE /technicalfeatures/1.json 
  def destroy
    @technicalfeature = Technicalfeature.find(params[:id])
    @technicalfeature.destroy
    
    respond_to do |format|
      format.html { redirect_to technicalfeatures_url }
      format.json { head :no_content }
    end
  end
  
  private
  
    def technicalfeature_params
      params.require(:technicalfeature).permit(:materialtype, :os, :name, :version, :memory, :ram, :processorfrequency)
    end
end

app/helpers/technicalfeatures_helper.rb
module TechnicalfeaturesHelper
end

app/views/technicalfeatures/_form.html.erb
<%= form_for(@technicalfeature) do |f| %>
  <% if @technicalfeature.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@technicalfeature.errors.count, "error") %>
prohibited this user from being saved:</h2>
    <ul>
    <% @technicalfeature.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
 <div class="field">
    <%= f.label :os %><br />
    <%= f.text_field :os %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :memory %><br />
    <%= f.text_field :memory %>
  </div>
    <div class="field">
    <%= f.label :ram %><br />
    <%= f.text_field :ram %>
  </div>
    <div class="field">
    <%= f.label :processorfrequency %><br />
    <%= f.text_field :processorfrequency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technicalfeatures/_technicalfeature.html.erb
<%= div_for technicalfeature do %>
  
	<div class="feature"> <div class="labelfeature">OS : </div>	<%= simple_format technicalfeature.os %> </div>

	<div class="feature"> <div class="labelfeature">Name : </div>	<%= simple_format technicalfeature.name %> </div>

	<div class="feature"> <div class="labelfeature">Version :</div>	<%= simple_format technicalfeature.version%> </div>

	<div class="feature"> <div class="labelfeature">Memory : </div>	<%= simple_format technicalfeature.memory.to_s() %> </div>

	<div class="feature"> <div class="labelfeature">RAM :</div>	<%= simple_format technicalfeature.ram.to_s() %> </div>

	<div class="feature"> <div class="labelfeature">Processor frequency : </div>	<%= simple_format technicalfeature.processorfrequency.to_s() %> </div>
	
  
	<%= link_to "Edit", edit_technicalfeature_path(technicalfeature) %>
	<%= link_to 'Destroy', technicalfeature, method: :delete, data: { confirm: 'Are you sure?' } %>
  
<% end %>

app/views/technicalfeatures/edit.html.erb
<h3>Edit technicalfeature</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', technicalfeatures_path %>

app/views/technicalfeatures/index.html.erb
<h3>List of technicalfeatures</h3>

<div id="technicalfeatures">
  <%= render @technicalfeatures %>
</div>

app/views/technicalfeatures/new.html.erb
<h3>New technical feature</h3>

<%= render 'form' %>

<%= link_to 'Back', technicalfeatures_path %>

app/views/technicalfeatures/show.html.erb
<%= render @technicalfeature %>