config/routes.rb
Gestionemprunts::Application.routes.draw do
  resources :carts

	get "materials/by_type", :controller=>"materials", :action=>"by_type"
	root :to => "requests#new"
	resources :users
	resource :session, :only => [:new, :create, :destroy]
	get '/login' => "sessions#new", :as => "login"
	get '/logout' => "sessions#destroy", :as => "logout"
	
	get '/requests/newtwo' => "requests#newtwo"
	
	resources :complexdates
	resources :technicalfeatures
	resources :materials
	resources :requests
	resources :materialgroups
	resources :materialtypes
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  has_many :cartlistmaterials
  has_many :cartitems, :through => :cartlistmaterials, :source => :technicalfeature
 
end

app/models/cartlistmaterial.rb
class Cartlistmaterial < ActiveRecord::Base
  
  belongs_to :cart
  belongs_to :technicalfeature
  
end

app/models/complexdate.rb
class Complexdate < ActiveRecord::Base
		
		#je me souviens plus si les heures sont obligatoires, il me semble que nn
		validates_presence_of :cdate
		
		belongs_to :request	
		belongs_to :complexdatetype
end

app/models/complexdatetype.rb
class Complexdatetype < ActiveRecord::Base
  
    validates_presence_of :label
    
    has_many :complexdates
    
end

app/models/material.rb
class Material < ActiveRecord::Base
  
  validates_presence_of :serialnumber
  validates_uniqueness_of :serialnumber
  
	has_and_belongs_to_many :requests
	
	belongs_to :materialgroup
	belongs_to :materialstatus
	belongs_to :technicalfeature
	
	has_one :type, :through=>:technicalfeature, :source=>:materialtype
end

app/models/materialgroup.rb
class Materialgroup < ActiveRecord::Base
  
  validates_presence_of :label, :site
  
	has_and_belongs_to_many :users
end

app/models/materialstatus.rb
class Materialstatus < ActiveRecord::Base
  
  validates_presence_of :label
  
  has_many :materials
end

app/models/materialtype.rb
class Materialtype < ActiveRecord::Base

	has_many :technicalfeatures
	has_many :associated_materials, :through=>:technicalfeatures, :source=>:materials
end

app/models/privilege.rb
class Privilege < ActiveRecord::Base

  validates_presence_of :label

	has_many :users

end

app/models/request.rb
class Request < ActiveRecord::Base	
  
  validates_presence_of :borrowmotive

  # Relations
	belongs_to :user
	has_many :complexdates
	has_and_belongs_to_many :materials
	belongs_to :requeststatus
	
end

app/models/requeststatus.rb
class Requeststatus < ActiveRecord::Base
  
  validates_presence_of :label
  
  has_many :requests
end

app/models/technicalfeature.rb
class Technicalfeature < ActiveRecord::Base
  
  has_many :materials
  belongs_to :materialtype
  
  has_one :technicalfeaturequantity
  
  has_many :cartlistmaterials
  has_many :techitems, :through => :cartlistmaterials, :source => :car
  
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

	# As the attribute :password does not exists as a column in the DB,
	# this defines an accessor attribute.
	# Like a local variable, just used to stock temporarely the not encrypted version of the password provided by the user.
	# Not persisted in the DB.
	attr_accessor :password

	# Global validation
	validates_presence_of :firstname, :lastname, :email
	
	# Email validations
	validates_uniqueness_of :email
	validates_length_of :email, :within => 5..50
	validates_format_of :email, :with =>  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	# Password validation
	validates_confirmation_of :password
	# validates_length_of :password, :within => 4..20
	# validates_presence_of :password, :if => :password_required?

	# Relations
	belongs_to :privilege
	has_many :requests
	has_many :appointments, :through=>:requests, :source=>:complexdates
	has_and_belongs_to_many :materialgroups
	
	# Always keep an encrypted version of the password in DB
	before_save :encrypt_new_password
	
	# Use --> User.authenticate('romain@gmail.com', 'password')
	# return the User object
	def self.authenticate(email, password)
		user = find_by_email(email)
		return user if user && user.authenticated?(password)
	end
	
	# Check the password
	def authenticated?(password)
		self.hashed_password == encrypt(password)
	end
	
	# Protected methods, used only inside the class
	protected
	
		# Create a new encrypted version of the password
		# Exit when local variable password is blank
		def encrypt_new_password
			return if password.blank?
			self.hashed_password = encrypt(password)
		end
		
		# Check if the password is required
		# When validating the password presence, if returns true, the :password local variable must be provided
		def password_required?
			hashed_password.blank? || password.present?
		end
		
		# Return the encrypted version of a string param
		def encrypt(string)
			Digest::SHA1.hexdigest(string)
		end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/complexdates_helper.rb
module ComplexdatesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emprunt de mat&eacute;riel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<% if logged_in? %>	
	<header>
		<!--<h1> Emprunts de mat&eacute;riel | Polytech Nice-Sophia </h1>-->
		
			<nav id="main_menu">
					<%= link_to 'Gérer les demandes', users_path %><!--
					--><%= link_to 'Faire une demande', new_request_path %><!--
					--><%= link_to 'Etat du stock', root_path %><!--
					--><%= link_to 'Matériel', root_path %>
			</nav>
	</header>
<% end %>

<section id="main_content" class="wrapper" data-role="page">
	<%= yield %>
</section>

</body>
</html>

app/views/layouts/old.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emprunt de mat&eacute;riel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<header>
	<h1> Emprunts de mat&eacute;riel | Polytech Nice-Sophia </h1>
	<% if logged_in? %>	
		<nav>
			<%= link_to 'Gérer les demandes', root_path %> |
			<%= link_to 'Faire une demande', root_path %> |
			<%= link_to 'Etat du stock', root_path %> |
			<%= link_to 'Matériel', root_path %> |
			<div id="user_actions">
				<%= link_to "Logout", logout_path %>
			</div>
		</nav>
	<% end %>
</header>


<% if logged_in? %>	
	<aside id="left_column" class="wrapper">
	
		<%= render current_user %>
		<header> iPad Air </header>
		<p>Batterie au lithium-polymère rechargeable intégrée de 32,4 Wh
		Jusqu’à 10 heures d’autonomie pour naviguer sur Internet en WiFi, regarder des vidéos ou écouter de la musique
		Jusqu’à 9 heures d’autonomie pour naviguer sur Internet via un réseau de données cellulaires
		Recharge via l’adaptateur secteur ou le port USB d’un ordinateur</p>
	</aside>
	<section id="main_content" class="wrapper">
		<header> Main Content </header>
		<%=yield%>
	</section>

<% else %>
	<section id="main_content" class="wrapper">
		<header> Main Content </header>
		<%= yield %>
	</section>	
	
<% end %>

</body>
</html>